[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hireverse"
version = "0.1"
requires-python = ">=3.9"

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}